services:
  gcloud-pubsub-emulator:
    image: bigtruedata/gcloud-pubsub-emulator
    command: 'start --host-port 0.0.0.0:8538'
    expose:
      - 8538

  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator
    command: -host 0.0.0.0 -port 8123 -queue "projects/test/locations/location/queues/nest-cloud-run-queue-demo"
    expose:
      - 8123

  demo:
    image: node:alpine
    command: sh -c "npm ci && cd packages/demo && npm run start:demo"
    volumes:
      - .:/work:delegated
      - node_modules:/work/node_modules
    working_dir: /work
    ports:
      - "3000:3000"
    depends_on:
      - gcloud-pubsub-emulator
      - gcloud-tasks-emulator
    environment:
      GOOGLE_CLOUD_PROJECT: test
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator:8538
      WORKER_ENDPOINT: http://demo:3000

volumes:
  node_modules:
