export const CLOUD_RUN_TASKS_PUBLISHER_MODULE_OPTIONS = "CLOUD_RUN_TASKS_PUBLISHER_MODULE_OPTIONS";
export const CLOUD_RUN_TASKS_CLIENT = "CLOUD_RUN_TASKS_CLIENT";

export const ERROR_QUEUE_NOT_FOUND = "Queue not found. Please set queue name.";
