export const CLOUD_RUN_PUBSUB_PUBLISHER_MODULE_OPTIONS = "CLOUD_RUN_PUBSUB_PUBLISHER_MODULE_OPTIONS";
export const CLOUD_RUN_PUBSUB = "CLOUD_RUN_PUBSUB";

export const ERROR_TOPIC_NOT_FOUND = "Topic not found. Please set topic name.";
